/*
 This file was generated by Dashcode and is covered by the
 license.txt included in the project.  You may edit this file,
 however it is recommended to first turn off the Dashcode
 code generator otherwise the changes will be lost.
 */
var dashcodePartSpecs = {
    "CompletedText": { "text": "Completed", "view": "DC.Text" },
    "CopyrightText": { "text": "Copyright © 2009-2010 Justin Paulin", "view": "DC.Text" },
    "DoneButton": { "creationFunction": "CreateGlassButton", "onclick": "showFront", "text": "Done" },
    "helloText": { "text": "Hello, World!", "view": "DC.Text" },
    "info": { "backgroundStyle": "black", "creationFunction": "CreateInfoButton", "foregroundStyle": "white", "frontID": "front", "onclick": "showBack" },
    "infobutton": { "backgroundStyle": "black", "creationFunction": "CreateInfoButton", "foregroundStyle": "white", "frontID": "front", "onclick": "showBack" },
    "SubjectText": { "text": "Subject", "view": "DC.Text" },
    "text": { "text": "", "view": "DC.Text" },
    "text1": { "text": "Version: 1.1", "view": "DC.Text" },
    "TitleText": { "text": "The Homework helper", "view": "DC.Text" },
    "WhatText": { "text": "What", "view": "DC.Text" }
};



